name: "🎉 功能建议"
title: "[Feature] "
description: 向我们提交一个新的功能想法或建议。
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: 描述
      description: 详细描述您希望添加的功能。

  - type: textarea
    attributes:
      label: 使用场景
      description: 这个功能的使用场景。

  - type: checkboxes
    attributes:
      label: 检查清单
      options:
        - label: 我已在 [Issue 列表](https://github.com/AstrBotDevs/AstrBot/issues)中搜索过相关问题仍无法解决，或该问题从未被报告过。
        - label: 我已经尝试过停用所有插件，排除插件导致的问题。
        - label: 我报告的问题与 AstrBot 本体相关，而非在报告某一插件的问题。
        - label: 我已阅读并同意本项目的[贡献者行为准则](https://github.com/AstrBotDevs/AstrBot/blob/master/CODE_OF_CONDUCT.md)。
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: 你愿意提交 PR 吗？
      description: 这不是必需的，但我们很乐意在你的贡献过程中提供指导，特别是如果你已经很好地理解了如何实现修复。
      options:
        - label: 我愿意提交 PR 以帮助实现该功能。

  - type: markdown
    attributes:
      value: "感谢您的建议！"
