name: Auto Assign Pull Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-assign:
    runs-on: ubuntu-24.04
    steps:
      - name: Auto Assign
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          assignees: QingFeng-awa
