name: Trigger API on Push

on:
  push:
    branches: [ main ]

env:
  PANEL_TOKEN: ${{ secrets.PANEL_TOKEN }}

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Get current timestamp
        id: timestamp
        run: echo "CURRENT_TIMESTAMP=$(date +%s)" >> $GITHUB_ENV

      - name: Call API
        run: |
          response=$(curl -s -X 'POST' \
            'http://panel.qingfengawa.top:11451/api/v1/cronjobs/handle' \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "1Panel-Token: ${{ env.PANEL_TOKEN }}" \
            -H "1Panel-Timestamp: ${{ env.CURRENT_TIMESTAMP }}" \
            -d '{
              "id": 11
            }')
            
          code=$(echo $response | jq -r '.code')
          
          if [ "$code" != "200" ]; then
            echo "API call failed with response: $response"
            exit 1
          else
            echo "API call succeeded"
          fi

      - name: Verify success
        if: ${{ failure() }}
        run: exit 1
