name: Auto Assign Pull Request

on:
  pull_request:
    types: [opened, ready_for_review]

permissions:
  contents: read
  pull-requests: write
  
jobs:
  auto-assign:
    runs-on: ubuntu-24.04
    steps:
      - name: Auto Assign
        uses: actions/github-script@v7
        with:
          script: |
            const assignees = ['QingFeng-awa'];
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              assignees: assignees
            });
