name: Trigger API on Push

on:
  push:
    branches: [ main ]

env:
  PANEL_API_KEY: ${{ secrets.PANEL_API_KEY }}  # 面板 API 密钥（Secrets 存储）
  API_BASE_URL: ${{ secrets.API_BASE_URL }}    # API 地址（Secrets 存储）

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Timestamp and Token
        id: auth
        run: |
          # 生成时间戳和 Token（禁止打印到日志）
          timestamp=$(date +%s)
          token=$(echo -n "1panel${{ env.PANEL_API_KEY }}${timestamp}" | md5sum | awk '{print $1}')
          
          # 通过掩码隐藏敏感信息（GitHub 自动屏蔽）
          echo "::add-mask::$token"
          echo "PANEL_TOKEN=${token}" >> $GITHUB_ENV
          echo "TIMESTAMP=${timestamp}" >> $GITHUB_ENV

      - name: Call API (Secure Mode)
        run: |
          # 禁止打印完整 curl 命令（避免泄露 Header）
          api_url="${{ env.API_BASE_URL }}/api/v1/cronjobs/handle"
          response=$(curl -s -X 'POST' \
            "$api_url" \
            -H 'accept: application/json' \
            -H 'Content-Type: application/json' \
            -H "1Panel-Token: ${{ env.PANEL_TOKEN }}" \
            -H "1Panel-Timestamp: ${{ env.TIMESTAMP }}" \
            -d '{"id": 10}' 2>&1)

          # 仅打印 code 字段（隐藏完整响应）
          code=$(echo "$response" | jq -r '.code')
          echo "API Response Code: $code"
          [ "$code" = "200" ] || exit 1
