name: Approve PR on command
on:
  issue_comment:
    types: [created]

jobs:
  check-and-approve:
    runs-on: ubuntu-latest
    steps:
    - name: Check for /approve command
      if: github.event.issue.pull_request && contains(github.event.comment.body, '/approve')
      id: check_approve
      uses: actions/github-script@v6
      with:
        script: |
          // 获取评论者用户名
          const commenter = context.payload.comment.user.login;
          
          // 验证评论者是否为 QingFneg-awa
          if (commenter === 'QingFneg-awa') {
            // 获取 PR 编号
            const prNumber = context.payload.issue.number;
            
            // 创建 PR 批准
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              event: 'APPROVE'
            });
            
            return 'PR approved by authorized user';
          } else {
            return 'Approval attempt by unauthorized user: ' + commenter;
          }
