name: Add milestone to PR
on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  add-milestone:
    runs-on: ubuntu-latest
    steps:
      - name: Add v2 milestone to PR
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              milestone: 1
            })
